# Generated by Django 5.0.3 on 2024-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasoned', '0002_seasoned_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoned',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
