# Generated by Django 5.0.3 on 2024-03-05 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('postTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
