# Generated by Django 5.0.3 on 2024-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='experience',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
