# Generated by Django 5.0.3 on 2024-03-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internship_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
