# Generated by Django 5.0.3 on 2024-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fresher',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
