# Generated by Django 5.0.3 on 2024-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
