# Generated by Django 5.0.3 on 2024-03-05 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0002_fresher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresher',
            name='postTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
