# Generated by Django 5.0.3 on 2024-03-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0003_alter_fresher_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='experience',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
